version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "docs"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"

  - package-ecosystem: "npm"
    directory: "/tests"
    schedule:
      interval: "weekly"
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "testing"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    allow:
      # These packages require timely updates for security
      - dependency-name: "selenium-webdriver"
      - dependency-name: "chromedriver"
      - dependency-name: "playwright"
      - dependency-name: "puppeteer"
